# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: danmu.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 2, "", "danmu.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x64\x61nmu.proto\x12\x05\x64\x61nmu"\x83\x01\n\nBulletInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\n\n\x02\x61\x33\x18\x03 \x01(\t\x12\n\n\x02\x61\x34\x18\x04 \x01(\t\x12\n\n\x02\x61\x35\x18\x05 \x01(\t\x12\x10\n\x08showTime\x18\x06 \x01(\t\x12\n\n\x02\x61\x37\x18\x07 \x01(\t\x12\n\n\x02\x61\x38\x18\x08 \x01(\t\x12\n\n\x02\x61\x39\x18\t \x01(\t".\n\x05\x45ntry\x12%\n\nbulletInfo\x18\x02 \x03(\x0b\x32\x11.danmu.BulletInfo"$\n\x05\x44\x61nmu\x12\x1b\n\x05\x65ntry\x18\x06 \x03(\x0b\x32\x0c.danmu.Entry'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "danmu_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_BULLETINFO"]._serialized_start = 23
    _globals["_BULLETINFO"]._serialized_end = 154
    _globals["_ENTRY"]._serialized_start = 156
    _globals["_ENTRY"]._serialized_end = 202
    _globals["_DANMU"]._serialized_start = 204
    _globals["_DANMU"]._serialized_end = 240
# @@protoc_insertion_point(module_scope)
